function [  u_nPlusHf4 ] = kron_fun_convec( u_nPlusHf2, matrix_A6x, matrix_Delta_x, S_n, S_nplus, matrix_Delta_y, matrix_A6y, dt,Ix, Iy )
 
%  B_all = kron( Iy, matrix_A6x )* kron( matrix_A6y, Ix ) ;
%      u_nPlusHf3  = B_all\( B_all*u_nPlusHf2 - dt*kron( matrix_A6y, Ix )*kron( Iy, matrix_Delta_x )  * fun_f(u_nPlusHf2)...
%                              - dt*kron( Iy, matrix_A6x )*kron(matrix_Delta_y, Ix ) *fun_g(u_nPlusHf2) ...
%                              + dt* B_all*S_n ) ;% + mt*(kxi + lam_n.*gprime(u_n));   %g
% 
%     u_nPlusHf4    = B_all\( B_all*u_nPlusHf3 - dt/2*kron( matrix_A6y, Ix )*kron( Iy, matrix_Delta_x )  * ( fun_f(u_nPlusHf2) + fun_f(u_nPlusHf3) )...
%                              - dt/2*kron( Iy, matrix_A6x )*kron(matrix_Delta_y, Ix ) *(fun_g(u_nPlusHf2) + fun_g(u_nPlusHf3) ) ...
%                              + dt/2* B_all*( S_n + S_nplus ) ) ; %+ mt*(kxi + lam_n.*gprime(u_n)); %g;
 
   u_nPlusHf3  =  u_nPlusHf2  - dt* ( kron( Iy, matrix_A6x ) \kron( Iy, matrix_Delta_x ) ) * fun_f(u_nPlusHf2)...
                             - dt*( kron( matrix_A6y, Ix )\kron(matrix_Delta_y, Ix ) )*fun_g(u_nPlusHf2) ...
                             + dt* S_n   ;% + mt*(kxi + lam_n.*gprime(u_n));   %g

    u_nPlusHf4    =  u_nPlusHf2  - dt/2* ( kron( Iy, matrix_A6x ) \kron( Iy, matrix_Delta_x ) ) * ( fun_f(u_nPlusHf2) + fun_f(u_nPlusHf3))...
                             - dt/2*( kron( matrix_A6y, Ix )\kron(matrix_Delta_y, Ix ) )* ( fun_g(u_nPlusHf2)+ fun_g(u_nPlusHf3)) ...
                             + dt/2* (S_n+ S_nplus)  ; %+ mt*(kxi + lam_n.*gprime(u_n)); %g;
end
 

